version: '2.1'

services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: rater-web-db
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
        networks: 
            jrater-network:
                aliases:
                    - jrater-db
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
                  
    jrater-spring:
        build: ./App
        ports:
            - "8080:8080"
        depends_on:
            mysql:
                condition: service_healthy
        links:
            - mysql
        volumes:
            - ${projects_path}:/webapp/students
            - ${references_path}:/webapp/references
            - ${jplag_dir}:/webapp/jplag
        networks: 
            jrater-network:
                aliases: 
                    - jrater-app

networks: 
    jrater-network:
